version: 0.0.1-{branch}-{build}

skip_tags: false
skip_non_tags: false
skip_branch_with_pr: false

image: Visual Studio 2017

clone_folder: C:\projects\build
shallow_clone: false
clone_depth: 5

environment:
  global:
    CUDA_VERSION: 10.0
    CUDA_PACKAGE: cuda_10.0.130_411.31_win10.exe
    CUDA_PACKAGE_URL: https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_win10
    CUDA_PACKAGE_CHECKSUM: 90fafdfe2167ac25432db95391ca954e
    CUDA_BASE_PATH: C:\CUDA
    CUDA_PATH: C:\CUDA\v10.0
    CUDA_PATH_v10_0: C:\CUDA\v10.0
  matrix:
    - MSBUILD_CONF: Debug
    - MSBUILD_CONF: Release

platform: x64

matrix:
  fast_finish: false

init:
# Replaces the placeholder version with a custom format: BUILD_NUMBER-BRANCH-SHORT_GIT_SHA
  - ps: Update-AppveyorBuild -Version "$env:appveyor_build_number-$env:appveyor_repo_branch-$($env:appveyor_repo_commit.substring(0,7))"
  - systeminfo
# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
  - git config --global core.autocrlf true

install: |
  if NOT EXIST %CUDA_BASE_PATH% mkdir %CUDA_BASE_PATH%
  if NOT EXIST %CUDA_PATH% (appveyor DownloadFile %CUDA_PACKAGE_URL% -FileName %CUDA_PACKAGE%)
  if NOT EXIST %CUDA_PATH% (7z x %CUDA_PACKAGE% -o%CUDA_BASE_PATH% nvcc/* nvrtc*/*)
  if NOT EXIST %CUDA_PATH% (rename %CUDA_BASE_PATH%\nvcc v%CUDA_VERSION%)
  set PATH=%CUDA_PATH%\bin;%PATH%
  set CUDA_TOOLKIT_ROOT_DIR=%CUDA_PATH%
  nvcc -V

build_script: |
  call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  echo %PATH%
  dir %CUDA_BASE_PATH%
  dir %CUDA_PATH%
  set CMAKE_ARGS=-G "Visual Studio 15 2017 Win64" -Bbuild -T cuda=10.0,host=x64 -D CMAKE_CUDA_COMPILER="%CUDA_PATH%\bin\nvcc.exe" .
  cmake %CMAKE_ARGS%
  cmake --build build --config %MSBUILD_CONF% --target ALL_BUILD

cache:
  - C:\CUDA\v%CUDA_VERSION% -> appveyor.yml

artifacts:
  - name: Cuda Mean Miner 64-bit for Windows (Release)
    path: build\Release\cuda29.exe
  - name: Cuda Mean Miner 64-bit for Windows (Debug)
    path: build\Debug\cuda29.exe
  - name: Cuda Lean Miner 64-bit for Windows (Release)
    path: build\Release\lcuda29.exe
  - name: Cuda Lean Miner 64-bit for Windows (Debug)
    path: build\Debug\lcuda29.exe

deploy: off
